apiVersion: v2
description: Helm chart for infrastructure services
name: infra
version: 0.1.0
appVersion: "0.1.0"
sources:
- https://github.com/rheghnairoh/openmf-phee
maintainers:
- name: Honest Chirozva
  email: hchirozvah@outlook.com
dependencies:
## kafka 
# - name: kafka
#   alias: kafka
#   condition: kafka.enabled
#   repository: oci://registry-1.docker.io/bitnamicharts
#   version: 26.2.0
## redpanda kafka console 
- name: console
  alias: redpanda-console
  condition: console.enabled
  repository: https://charts.redpanda.com
  version: 0.7.6
## MongoDB
- name: mongodb
  alias: mongodb
  condition: mongodb.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 14.12.2
## Mongo-express
- name: mongo-express
  alias: mongo-express
  condition: mongo-express.enabled
  repository: https://cowboysysop.github.io/charts/
  version: 5.2.0
## redis 
# - name: redis
#   alias: redis 
#   condition: redis.enabled
#   repository: https://charts.bitnami.com/bitnami
#   version: 18.1.6
# ## Elastic Search Kibana 
# - name: elasticsearch
#   alias: elasticsearch
#   condition: elasticsearch.enabled
#   repository: oci://registry-1.docker.io/bitnamicharts
#   version: 19.13.5