############### RedPanda Console for Kafka  ####################
# https://artifacthub.io/packages/helm/redpanda-data/console?modal=values
# redpanda kakfa console config

redpanda-console:
  enabled: true
  fullnameOverride: rpconsole

  console:
    config:
      kafka:
        brokers:
          - kafka.g2p-sandbox.svc.cluster.local:9092

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: redpanda-console.local
        paths:
          - path: /
            pathType: ImplementationSpecific

############### MongoDB  ####################
# https://github.com/bitnami/charts/tree/main/bitnami/mongodb
mongodb:
  enabled: true
  image:
    tag: 4.4.15-debian-10-r8

  fullnameOverride: "mongodb"
  auth:
    enabled: true

    rootUser: root
    rootPassword: mongoDbPas42
    usernames:
    - 'mifos'
    passwords:
    - 'password'
    databases:
    - 'paymenthub'

    replicaSetKey: ""
    existingSecret: ""
  persistence:
    enabled: false

############### Mongo Express ####################
# mongo express config
mongo-express:
  fullnameOverride: mongo-express
  enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx

  mongodbEnableAdmin: true
  mongodbAdminPassword: mongoDbPas42
