############### RedPanda Console for Kafka  ####################
# https://artifacthub.io/packages/helm/redpanda-data/console?modal=values
# redpanda kakfa console config

redpanda-console:
  enabled: true
  fullnameOverride: rpconsole

  console:
    config:
      kafka:
        brokers:
          - kafka.paymenthub.svc.cluster.local:9092

  ingress:
    enabled: true
    className: public
    hosts:
      - host: redpanda-console.local
        paths:
          - path: /
            pathType: ImplementationSpecific

############### MongoDB  ####################
# https://github.com/bitnami/charts/tree/main/bitnami/mongodb
mongodb:
  enabled: true
  image:
    tag: 4.4.15-debian-10-r8

  fullnameOverride: "mongodb"
  auth:
    enabled: true

    rootUser: root
    rootPassword: mongoDbPas42
    usernames:
      - "mifos"
    passwords:
      - "password"
    databases:
      - "paymenthub"

    replicaSetKey: ""
    existingSecret: ""
  persistence:
    enabled: false

############### Mongo Express ####################
# mongo express config
mongo-express:
  fullnameOverride: mongo-express
  enabled: true

  ingress:
    enabled: true
    ingressClassName: public

  mongodbEnableAdmin: true
  mongodbAdminPassword: mongoDbPas42

kafka:
  enabled: false
  fullnameOverride: "kafka"

  persistence:
    enabled: false

  controller:
    replicaCount: 1

  zookeeper:
    persistence:
      enabled: true

    fullnameOverride: "zookeeper"

  provisioning:
    enabled: true
    numPartitions: 1
    replicationFactor: 1
    topics:
      - name: zeebe-export
        partitions: 1
        replicationFactor: 1
      - name: KAFKA_AUDITS_TOPIC
        value: audits
      - name: KAFKA_LOGS_TOPIC
        value: logs
      - name: AccountLookupBcRequests
        value: AccountLookupBcRequests
      - name: AccountLookupBcEvents
        value: AccountLookupBcEvents
      - name: AccountLookupBcResponses
        value: AccountLookupBcResponses
      - name: AccountLookupBcErrors
        value: AccountLookupBcErrors
      - name: OperatorBcErrors
        value: OperatorBcErrors
      - name: QuotingBcErrors
        value: QuotingBcErrors
      - name: QuotingBcEvents
        value: QuotingBcEvents
      - name: QuotingBcRequests
        value: QuotingBcRequests
      - name: SettlementsBcRequests
        value: SettlementsBcRequests
      - name: TransfersBcErrors
        value: TransfersBcErrors
      - name: TransfersBcEvents
        value: TransfersBcEvents
      - name: TransfersBcRequests
        value: TransfersBcRequests
      - name: SettlementsBcEvents
        value: SettlementsBcEvents
      - name: SettlementsBcCommands
        value: SettlementsBcCommands
      - name: PlatformConfigurationBcEvents
        value: PlatformConfigurationBcEvents
