ph-ee-g2psandbox:
  ph-ee-engine:
    global:
      SPRING_PROFILES_ACTIVE: "bb"
      LOGGING_LEVEL_ROOT: "INFO"
      tenants: "rhino,gorilla,lion"
      DFSPIDS: "gorilla,lion"

    camunda-platform:
      prometheusServiceMonitor:
        enabled: false

    zeebe-cluster-helm:
      enabled: true

      elasticsearch:
        enabled: false
      kibana:
        enabled: true

    zeebe-operate-helm:
      ingress:
        enabled: false
        annotations: 
          kubernetes.io/ingress.class: public
        path: /
        host: operate.sandbox.fynarfin.io
        tls:
          enabled: true

    elasticsearch:
      enabled: true
      volumeClaimTemplate:
        # accessModes: [ "ReadWriteOnce" ]
        storageClassName: "microk8s-hostpath"
        resources:
          requests:
            storage: 10Gi

    kibana:
      ingress:
        enabled: true
        className: "public"
        pathtype: "Prefix"
        annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        hosts:
          - host: analytics.sandbox.fynarfin.io
            paths:
              - path: /

    operations:
      enabled: true
      mysql:
        enabled: false

    operationsmysql:
      enabled: false

    ph_ee_connector_ams_mifos:
      enabled: true

      operations_app:
        datasource:
          host: "operationsmysql.sandbox.fynarfin.io"
      deployment:
        annotations:
          rollme: '{{ randAlphaNum 5 | quote }}'
      ams_local_interop_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_account_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_customer_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_auth_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_loan_host: "https://fynams.sandbox.fynarfin.io/"
      ingress:
        enabled: true 
        hosts:
          - host: ams-mifos.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-ams-mifos
                  port:
                    number: 80
          - host: ams-mifos-mock.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: ph-ee-connector-ams-mifos
                    port:
                      number: 7070

    ph_ee_connector_mojaloop:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-mojaloop:latest
      switch:
        quotes:
          host: "http://quoting-service.sandbox.fynarfin.io"
          service: "quoting-service.sandbox.fynarfin.io"
        als:
          host: "http://account-lookup-service.sandbox.fynarfin.io"
          service: "account-lookup-service.sandbox.fynarfin.io"
        transfers:
          host: "http://ml-api-adapter.sandbox.fynarfin.io"
          service: "api-adapter.sandbox.fynarfin.io"
        transactions:
          host: "http://ml-api-adapter.sandbox.fynarfin.io"
          service: "ml-api-adapter.sandbox.fynarfin.io"
        oracle:
          host: "http://moja-simulator.sandbox.fynarfin.io"
      deployment:
        extraEnvs:
          - name: parties_0_domain
            value: "https://fynams.sandbox.fynarfin.io/"
          - name: parties_1_domain
            value: "mojaloop.sandbox.fynarfin.io"
          - name: parties_0_tenantId
            value: "gorilla"
          - name: parties_1_tenantId
            value: "lion"
          - name: parties_0_fspId
            value: "payerfsp"
          - name: parties_1_fspId
            value: "payeefsp"

      ingress:
        enabled: true
        tls:
          - secretName: fyn-cert
        hosts:
          - host: mojaloop.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-mojaloop-java
                  port:
                    number: 80

    kafka:
      enabled: true
      fullnameOverride: kafka
      provisioning:
        enabled: true
        waitForKafka: true
        numPartitions: 1
        replicationFactor: 1
        topics:
        - name: zeebe-export
          partitions: 1
          replicationFactor: 1
        - name: KAFKA_AUDITS_TOPIC
          value: audits
        - name: KAFKA_LOGS_TOPIC
          value: logs
        - name: AccountLookupBcRequests
          value: AccountLookupBcRequests
        - name: AccountLookupBcEvents
          value: AccountLookupBcEvents
        - name: AccountLookupBcResponses
          value: AccountLookupBcResponses
        - name: AccountLookupBcErrors
          value: AccountLookupBcErrors
        - name: OperatorBcErrors
          value: OperatorBcErrors
        - name: QuotingBcErrors
          value: QuotingBcErrors
        - name: QuotingBcEvents
          value: QuotingBcEvents
        - name: QuotingBcRequests
          value: QuotingBcRequests
        - name: SettlementsBcRequests
          value: SettlementsBcRequests
        - name: TransfersBcErrors
          value: TransfersBcErrors
        - name: TransfersBcEvents
          value: TransfersBcEvents
        - name: TransfersBcRequests
          value: TransfersBcRequests
        - name: SettlementsBcEvents
          value: SettlementsBcEvents
        - name: SettlementsBcCommands
          value: SettlementsBcCommands
        - name: PlatformConfigurationBcEvents
          value: PlatformConfigurationBcEvents

    channel:
      enabled: true
      hostname: "channel.sandbox.fynarfin.io"
      stub_hostname: "channel-gsma.sandbox.fynarfin.io"
      SPRING_PROFILES_ACTIVE: "bb,tenants"
      DFSPIDS: "rhino,gorilla,lion"
      operations:
        url: "http://ph-ee-operations-app:5000/api/v1"
        authEnabled: false
      tenantPrimary:
        clientId: "mifos"
        clientSecret: "password"
        tenant: "rhino"
      tenantSecondary:
        clientId: "mifos"
        clientSecret: "password"
        tenant: "gorilla"
      server:
        ssl:
          keyPassword: "password"
          keyStorePassword: "password"   
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      service:
        annotations:
          konghq.com/protocol: "https"
      ingress:
        enabled: true 
        className: "kong"
        hosts:
          - host: channel.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel"
                  port:
                    number: 8443
          - host: channel-gsma.sandbox.fynarfin.io          
            paths:          
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel-gsma"
                  port:
                    number: 82  
             

    operations_app:
      enabled: true
      tenants: "rhino,gorilla"
      hostname: "ops-bk.sandbox.fynarfin.io"
      datasource:
        username: "mifos"
        password: "password"
        host: "operationsmysql.sandbox.fynarfin.io"
        port: 3306
        schema: "tenants"
      limits:
        memory: "2Gi"
        cpu: "1000m"
      requests:
        memory: "516M"
        cpu: "500m"  
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
          nginx.ingress.kubernetes.io/use-regex: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /$2
        hosts:
          - host: ""        
            paths: 
            - path: "/operations(/|$)(.*)"
              backend:
                service:
                  name: "ph-ee-operations-app"
                  port:
                    number: 80 

    operations_web:
      enabled: true
      image: docker.io/openmf/ph-ee-operations-web:latest
      hostname: "ops.sandbox.fynarfin.io"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: public
        hosts:
          - host: ops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-operations-web"
                  port:
                    number: 4200            

    identity:
      hostname: "ops-bk.sandbox.fynarfin.io"

    ph_ee_connector_gsma:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-gsma:latest
      ingress:
        enabled: true  

    ph_ee_connector_slcb:
      enabled: false
    
    mpesa:
      enabled: false
      
    roster_connector:
      enabled: false
      
    paygops_connector:
      enabled: false
      
    notifications:
      enabled: true
      image: docker.io/openmf/ph-ee-notifications:latest
      NOTIFICATION_FAILURE_ENABLED: "false"
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "512M"
        cpu: "100m"
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
        hosts:
          - host: notifications.sandbox.fynarfin.io         
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-notifications"
                  port:
                    number: 80 

    connector_bulk:
      enabled: true
      image: docker.io/openmf/ph-ee-bulk-processor:latest
      tenants: "rhino,gorilla"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      operations_app:
        contactpoint: "https://ops-bk.sandbox.fynarfin.io/"
        endpoints:
          batch_transaction: "/api/v1/batch/transactions"
      identity_account_mapper:
        hostname: "https://identity-mapper.sandbox.fynarfin.io"
      ingress:
        enabled: true
        className: "kong"
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: bulk-connector.sandbox.fynarfin.io     
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-bulk"
                  port:
                    number: 8443   
          
    zeebe_ops:
      enabled: true
      image: docker.io/openmf/ph-ee-zeebe-ops:latest
      hostname: "zeebeops.sandbox.fynarfin.io"
      tenants: "rhino,gorilla"
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
        hosts:
          - host: zeebeops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-zeebe-ops"
                  port:
                    number: 80

    messagegateway:
      enabled: true
      image: docker.io/openmf/message-gateway:latest
      MYSQL_USERNAME: "mifos"
      MYSQL_PASSWORD: "password"
      DATASOURCE_URL: jdbc:mysql:thin://operationsmysql.sandbox.fynarfin.io:3306/messagegateway
      secret:
        value:
          api_key: "eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl"
          project_id: "PJ5ff552ce01d2978c"
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "512M"
        cpu: "100m"
      ingress:
        enabled: true   
        annotations: 
          kubernetes.io/ingress.class: public
        hosts:
          - host: messagegateway.sandbox.fynarfin.io       
            paths: 
            - path: "/"
              backend:
                service:
                  name: "message-gateway"
                  port:
                    number: 80
                            
    importer_es:
      enabled: true
      image: docker.io/openmf/ph-ee-importer-es:latest

    importer_rdbms:
      enabled: true
      image: docker.io/openmf/ph-ee-importer-rdbms:latest
      aws:
        region: "us-east-1"
      datasource:
        username: "mifos"
        password: "password"
        host: "operationsmysql.sandbox.fynarfin.io"
        port: 3306
        schema: "tenants"
    
    mockpayment:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-mock-payment-schema:latest
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
        hosts:
          - host: mockpaymentschema.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-mock-payment-schema"
                    port:
                      number: 8080

    billPay:
      enabled: true
      image: docker.io/openmf/ph-ee-bill-pay:latest
      billpay:
        contactpoint: "https://bill-pay.sandbox.fynarfin.io"
      connector:
        contactpoint: "https://connector.sandbox.fynarfin.io"
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
        hosts:
          - host: bill-pay.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-bill-pay"
                    port:
                      number: 8080
    crm:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-crm:latest
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
        hosts:
          - host: connector-crm.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-crm"
                    port:
                      number: 8080

    wildcardhostname: "*.sandbox.fynarfin.io"
    tls: ""

    post_installation_job: 
      enabled: true

    keycloak:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "kong"
        rules:
          - host: 'keycloak.sandbox.fynarfin.io'
            paths:
            - path: /
              pathType: Prefix

    kong:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "kong"
        hostname: admin-kong.sandbox.fynarfin.io 

    redis:
      enabled: true
      replica:
        replicaCount: 0

    vouchers:
      enabled: true
      image: docker.io/openmf/ph-ee-vouchers:latest
      spring:
        datasource:
          url: jdbc:mysql://operationsmysql.sandbox.fynarfin.io:3306/voucher_management
          username: mifos
          password: password
      voucher:
        hostname: "https://vouchers.sandbox.fynarfin.io"
      salting:
        enabled: true
      identity-account-mapper:
        hostname: "https://identity-mapper.sandbox.fynarfin.io"
      operations:
        hostname: "https://ops-bk.sandbox.fynarfin.io"
        endpoints:
          transfers: "/api/v1/transfers?size=1&page=0"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: vouchers.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-vouchers"
                    port:
                      number: 80
    connector:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-bulk:latest
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: public
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: connector.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector"
                    port:
                      number: 80
    minio:
      enabled: true
      consoleIngress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "public"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        hosts:
          - minio-console.sandbox.fynarfin.io

  account_mapper:
    enabled: true
    image: docker.io/openmf/ph-ee-identity-account-mapper:latest
    spring:
      datasource:
        url: jdbc:mysql:thin://operationsmysql.sandbox.fynarfin.io:3306/identity_account_mapper
        username: mifos
        password: password
    requests:
      cpu: "500m"
      memory: "512M"
    deployment:
      annotations:
        rollme: "{{ randAlphaNum 5 | quote }}"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: public
      tls:
        - secretName: sandbox-secret
      hosts:
        - host: identity-mapper.sandbox.fynarfin.io
          paths:
            - path: "/"
              backend:
                service:
                  name: "ph-ee-identity-account-mapper"
                  port:
                    number: 80

                  


